<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Cross-Lagged Analysis and ANCOVA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lim_homework_week_12_files/libs/clipboard/clipboard.min.js"></script>
<script src="lim_homework_week_12_files/libs/quarto-html/quarto.js"></script>
<script src="lim_homework_week_12_files/libs/quarto-html/popper.min.js"></script>
<script src="lim_homework_week_12_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lim_homework_week_12_files/libs/quarto-html/anchor.min.js"></script>
<link href="lim_homework_week_12_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lim_homework_week_12_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lim_homework_week_12_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lim_homework_week_12_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lim_homework_week_12_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">lim_homework_week_12</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="homework-12-antonio-vazquez-lim" class="level1">
<h1>Homework 12 – Antonio Vazquez Lim</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               lavaan, <span class="co"># SEM package</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               lm.beta, <span class="co"># for getting standardized beta coefficients</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               readxl, <span class="co"># reading xlsx files</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>               rstatix, <span class="co"># anova_test</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>               psych, <span class="co"># descriptive stats</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>               cowplot,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>               performance) <span class="co"># model assumption testing</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="part-1" class="level2">
<h2 class="anchored" data-anchor-id="part-1">Part 1</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loading data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dep_df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"hw12_part1.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dep_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  dep_t1 dep_t2 commun_t1 commun_t2
   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1   0.35   0.3        7       0.5  
2   1.15   1.35       2.9     0.667
3   0.2    0.2        7       0.833
4   0.05   0.05       7       1    
5   0      0.7        3.8     1    
6   0.9    0.95       6.5     1    </code></pre>
</div>
</div>
<section id="zero-order-correlations" class="level3">
<h3 class="anchored" data-anchor-id="zero-order-correlations">Zero-order correlations</h3>
<p>We first see if depression at <span class="math inline">\(t_1\)</span> is correlated with communication skills at <span class="math inline">\(t_2\)</span>, and see if communication skills at <span class="math inline">\(t_1\)</span> is correlated with depression at <span class="math inline">\(t_2\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(dep_df<span class="sc">$</span>dep_t1, dep_df<span class="sc">$</span>commun_t2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  dep_df$dep_t1 and dep_df$commun_t2
t = -2.8252, df = 137, p-value = 0.005431
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.38605579 -0.07090644
sample estimates:
       cor 
-0.2346371 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(dep_df<span class="sc">$</span>commun_t1, dep_df<span class="sc">$</span>dep_t2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  dep_df$commun_t1 and dep_df$dep_t2
t = -6.0178, df = 137, p-value = 1.527e-08
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.5796186 -0.3147032
sample estimates:
       cor 
-0.4572451 </code></pre>
</div>
</div>
<p>Yes, both pairs are correlated with one another such that for <span class="math inline">\(b_{\text{d}_{t_1} \rightarrow \text{c}_{t_2}} = -0.235, p &lt; .01\)</span> and <span class="math inline">\(b_{\text{c}_{t_1} \rightarrow \text{d}_{t_2}} = -0.457, p &lt; .001\)</span>.</p>
</section>
<section id="multiple-regression-for-cross-lagged-analysis" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-for-cross-lagged-analysis">Multiple regression for cross-lagged analysis</h3>
<p>Now we are going to do four things:</p>
<ol type="1">
<li>Create a model describing the stability of depression symptoms <span class="math inline">\(t_1 \rightarrow t_2\)</span></li>
<li>Create a model describing the stability of communication skills <span class="math inline">\(t_1 \rightarrow t_2\)</span></li>
<li>Regress depression symptoms at <span class="math inline">\(t_2\)</span> on those at <span class="math inline">\(t_1\)</span> and communication skills at <span class="math inline">\(t_1\)</span></li>
<li>Regress communication skills at <span class="math inline">\(t_2\)</span> on those at <span class="math inline">\(t_1\)</span> and depression symptoms at <span class="math inline">\(t_1\)</span></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regressing dep_t2 onto dep_t1 (stability)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>fit_dep_0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(dep_t2 <span class="sc">~</span> dep_t1, <span class="at">data =</span> dep_df)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># regressing commun_t2 onto commun_t1 (stability)</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>fit_comm_0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(commun_t2 <span class="sc">~</span> commun_t1, <span class="at">data =</span> dep_df)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># multiple regressions for cross-lagged analyses</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(dep_t2 <span class="sc">~</span> dep_t1 <span class="sc">+</span> commun_t1, <span class="at">data =</span> dep_df)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(commun_t2 <span class="sc">~</span> dep_t1 <span class="sc">+</span> commun_t1, <span class="at">data =</span> dep_df)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>fit_dep_0 <span class="sc">%&gt;%</span> <span class="fu">lm.beta</span>() <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = dep_t2 ~ dep_t1, data = dep_df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.75049 -0.14230 -0.04112  0.08388  0.90947 

Coefficients:
            Estimate Standardized Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.14230           NA    0.03294   4.320 2.98e-05 ***
dep_t1       0.49411      0.52793    0.06791   7.276 2.41e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.262 on 137 degrees of freedom
Multiple R-squared:  0.2787,    Adjusted R-squared:  0.2734 
F-statistic: 52.94 on 1 and 137 DF,  p-value: 2.415e-11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fit_comm_0 <span class="sc">%&gt;%</span> <span class="fu">lm.beta</span>() <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = commun_t2 ~ commun_t1, data = dep_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.5034 -0.5034  0.1633  0.8260  2.0443 

Coefficients:
            Estimate Standardized Std. Error t value Pr(&gt;|t|)    
(Intercept)  -1.5521           NA     1.0912  -1.422    0.157    
commun_t1     0.7936       0.3860     0.1621   4.897  2.7e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.101 on 137 degrees of freedom
Multiple R-squared:  0.149, Adjusted R-squared:  0.1427 
F-statistic: 23.98 on 1 and 137 DF,  p-value: 2.701e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="sc">%&gt;%</span> <span class="fu">lm.beta</span>() <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = dep_t2 ~ dep_t1 + commun_t1, data = dep_df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.58043 -0.13021 -0.02964  0.08458  0.95238 

Coefficients:
            Estimate Standardized Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.29713           NA    0.26920   4.818 3.81e-06 ***
dep_t1       0.39401      0.42098    0.06799   5.795 4.54e-08 ***
commun_t1   -0.16682     -0.31372    0.03863  -4.319 3.01e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2466 on 136 degrees of freedom
Multiple R-squared:  0.3657,    Adjusted R-squared:  0.3564 
F-statistic:  39.2 on 2 and 136 DF,  p-value: 3.599e-14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="sc">%&gt;%</span> <span class="fu">lm.beta</span>() <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = commun_t2 ~ dep_t1 + commun_t1, data = dep_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4829 -0.5330  0.1696  0.7587  2.5070 

Coefficients:
            Estimate Standardized Std. Error t value Pr(&gt;|t|)    
(Intercept)  -0.8526           NA     1.1973  -0.712    0.478    
dep_t1       -0.4221      -0.1166     0.3024  -1.396    0.165    
commun_t1     0.7119       0.3462     0.1718   4.144 5.98e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.097 on 136 degrees of freedom
Multiple R-squared:  0.161, Adjusted R-squared:  0.1486 
F-statistic: 13.05 on 2 and 136 DF,  p-value: 6.555e-06</code></pre>
</div>
</div>
<p>The results of our regressions indicate that depression at <span class="math inline">\(t_1\)</span> significantly predicts depression at <span class="math inline">\(t_2\)</span>, <span class="math inline">\(\beta_{d_1 \rightarrow d_2} = 0.53, p &lt; .001\)</span>, indicating that depression symptoms remain fairly stable over time. The same is true for communication skills remaining stable over the same time interval, <span class="math inline">\(\beta_{c_1 \rightarrow c_2} = 0.39, p &lt; .001\)</span>.</p>
<p>The cross-lagged analyses indicate that better communication skills at <span class="math inline">\(t_1\)</span> significantly predict less depression symptoms at <span class="math inline">\(t_2\)</span> while controlling for depression symptoms at <span class="math inline">\(t_1\)</span>, <span class="math inline">\(\beta_{c_1 \rightarrow d_2} = -0.31,\hspace{1mm} t(136) = -4.32,\hspace{1mm} p &lt; .001\)</span>. However, depression symptoms at <span class="math inline">\(t_1\)</span> remained a significant predictor of depression symptoms at <span class="math inline">\(t_2\)</span> while controlling for communication skills at <span class="math inline">\(t_1\)</span>, <span class="math inline">\(\beta_{d_1 \rightarrow d_2} = 0.42, t(136) = 5.80, p &lt; .001\)</span>.</p>
<p>Taken together these results suggest that, despite having good communication skills, one may not see a decrease in depression symptoms at a later time, but also that</p>
<p>The next multiple regression, with communication skills at <span class="math inline">\(t_2\)</span> regressed on depression symptoms and communication skills at <span class="math inline">\(t_1\)</span>, resulted in no significant association between depression symptoms at <span class="math inline">\(t_1\)</span> and communication skills at <span class="math inline">\(t_2\)</span> when controlling for communication skills at <span class="math inline">\(t_1\)</span>, <span class="math inline">\(\beta_{d_1 \rightarrow c_2} = -0.12, t(136) = -1.40, p = .17\)</span>. In other words, depression symptoms at <span class="math inline">\(t_1\)</span> do not predict any change in communication skills at <span class="math inline">\(t_2\)</span> beyond that change attributable to comunication skills at <span class="math inline">\(t_1\)</span>. However, controlling for depression symptoms at <span class="math inline">\(t_1\)</span>, it remained true that better communication skills at an earlier time predicted better communication skills in the future, even when with depression symptoms considered, <span class="math inline">\(\beta_{c_1 \rightarrow c_2} = 0.35, t(136) = 4.14, p &lt; .001\)</span>.</p>
<p>Taken together, these results suggest that depression does not lead to worse communication skills. Rather, poor communication skills may lead to worsening depression symptoms <em>or</em> better communication skills may lead to lessening depression symptoms. Even with communication skills considered, however, depression remains stable over time, and so it may be worth considering that depression symptoms do not resolve with solely good communication and further intervention may be necessary.</p>
</section>
</section>
<section id="part-2" class="level2">
<h2 class="anchored" data-anchor-id="part-2">Part 2</h2>
<p>Fetching the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>anorexia_data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"hw12_part2.xlsx"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(anorexia_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  Group Pretest Posttest  Gain
  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
1     1    80.5     82.2   1.7
2     1    84.9     85.6   0.7
3     1    81.5     81.4  -0.1
4     1    82.6     81.9  -0.7
5     1    79.9     76.4  -3.5
6     1    88.7    104.   14.9</code></pre>
</div>
</div>
<section id="multiple-regression" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression">Multiple regression</h3>
<p>First we will use regression to test our hypothesis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>fit0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Posttest <span class="sc">~</span> Pretest, <span class="at">data =</span> anorexia_data)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>fit1Pt2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Posttest <span class="sc">~</span> Pretest <span class="sc">+</span> Group, <span class="at">data =</span> anorexia_data)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>fit0 <span class="sc">%&gt;%</span> <span class="fu">lm.beta</span>() <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Posttest ~ Pretest, data = anorexia_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.6153  -5.2804  -0.7039   2.9941  17.7898 

Coefficients:
            Estimate Standardized Std. Error t value Pr(&gt;|t|)    
(Intercept)  54.8733           NA    15.0075   3.656 0.000588 ***
Pretest       0.3488       0.2542     0.1823   1.913 0.061140 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.035 on 53 degrees of freedom
Multiple R-squared:  0.0646,    Adjusted R-squared:  0.04695 
F-statistic:  3.66 on 1 and 53 DF,  p-value: 0.06114</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fit1Pt2 <span class="sc">%&gt;%</span> <span class="fu">lm.beta</span>() <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Posttest ~ Pretest + Group, data = anorexia_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.699  -3.944  -1.186   4.257  16.073 

Coefficients:
            Estimate Standardized Std. Error t value Pr(&gt;|t|)    
(Intercept)  56.2687           NA    14.4419   3.896 0.000281 ***
Pretest       0.3046       0.2219     0.1763   1.727 0.090064 .  
Group         4.2441       0.2967     1.8378   2.309 0.024929 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.764 on 52 degrees of freedom
Multiple R-squared:  0.1516,    Adjusted R-squared:  0.119 
F-statistic: 4.646 on 2 and 52 DF,  p-value: 0.01392</code></pre>
</div>
</div>
<p>Now the <span class="math inline">\(R^2\Delta\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.1516-0.0646</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.087</code></pre>
</div>
</div>
</section>
<section id="multiple-regression-write-up" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-write-up">Multiple regression write-up</h3>
<p>To test the effects of experimental condition on post-treatment anorexia test scores, we ran a multiple regression in which post scores on the DV were regressed first onto pre scores on the DV and then a variable indicating condition (- 1 = control, 1 = experimental condition). Pre-treatment anorexia scores, <span class="math inline">\(S_0\)</span>, were not significantly associated with post-treatment scores, <span class="math inline">\(S_f\)</span>, with <span class="math inline">\(\beta_{0\rightarrow 1} = .25, t(53) = 1.91, p = .06\)</span>, indicating that scores did not remain stable over the time interval. In the second regression, wherein the grouping factor was added into the model, group was a significant predictor of post-treatment test scores, <span class="math inline">\(\beta_{g\rightarrow S_f} = .30, t(52) = 2.31, p &lt; .05\)</span>. The second model captures a modest, but significant, 8.7% more variance (<span class="math inline">\(R^2 \Delta = 0.087\)</span>) than the model with only pre-treatment scores as a predictor.</p>
</section>
<section id="ancova" class="level3">
<h3 class="anchored" data-anchor-id="ancova">ANCOVA</h3>
<p>Now we just run an ANOVA and R automatically knows its an ANCOVA by the variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>res.aov <span class="ot">&lt;-</span> anorexia_data <span class="sc">%&gt;%</span> <span class="fu">anova_test</span>(Posttest <span class="sc">~</span> Pretest <span class="sc">+</span> Group)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_anova_table</span>(res.aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA Table (type II tests)

   Effect DFn DFd     F     p p&lt;.05   ges
1 Pretest   1  52 2.983 0.090       0.054
2   Group   1  52 5.333 0.025     * 0.093</code></pre>
</div>
</div>
<p>So, only group was significant. Now we do post-hocs for estimated marginal means and effect side (Cohen’s <span class="math inline">\(d\)</span>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>pws <span class="ot">&lt;-</span> anorexia_data <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">emmeans_test</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    Posttest <span class="sc">~</span> Group, <span class="at">covariate =</span> Pretest,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>pws<span class="sc">$</span>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02492918</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>pws<span class="sc">$</span>p.adj</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02492918</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_emmeans</span>(pws)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 8
  Pretest Group emmean    se    df conf.low conf.high method      
    &lt;dbl&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;       
1    82.2 0       81.3  1.33    52     78.6      84.0 Emmeans test
2    82.2 1       85.5  1.26    52     83.0      88.1 Emmeans test</code></pre>
</div>
</div>
<p>So, the estimated marginal means reveal that there is a significant difference in the post-treatment test scores by experimental group. Now Cohen’s <span class="math inline">\(d\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>rstatix<span class="sc">::</span><span class="fu">cohens_d</span>(Posttest <span class="sc">~</span> Group, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data=</span>anorexia_data, </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">paired =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  .y.      group1 group2 effsize    n1    n2 magnitude
* &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;ord&gt;    
1 Posttest 0      1       -0.676    26    29 moderate </code></pre>
</div>
</div>
<p>So, there is a moderate effect size <span class="math inline">\(d = |-0.68|\)</span>.</p>
</section>
<section id="ancova-write-up" class="level3">
<h3 class="anchored" data-anchor-id="ancova-write-up">ANCOVA write-up</h3>
<p>To evaluate the effects of the intervention on post-treatment anorexia test scores, we conducted an ANCOA test predicting the <span class="math inline">\(t_2\)</span> post-treatment scores with experimental group (1 = intervention, 0 = control) as a factor and pre-treatment scores as a covariate. Results of the ANCOVA indicated a significant effect of experimental group, controlling for pre-treatment anorexia scores, <span class="math inline">\(F(1, 52) = 5.33, p &lt; .05\)</span>. Adjusting for pre-treatment scores, the mean post-treatment scores were greater in the intervention group, <span class="math inline">\(\text{EMM}_{int} = 85.53, \text{SE} = 1.26\)</span>, than those in the control group, <span class="math inline">\(\text{EMM}_{control} = 81.29, \text{SE} = 1.33\)</span>, with this difference having a moderate effect size, <span class="math inline">\(d_c = -0.68\)</span>.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>
